version: '3.8'

services:
  app:
    build: .
    image: node:21-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    networks:
      - mynetwork
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
