# Generated by Django 5.0.4 on 2024-09-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_service_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('description', models.TextField(verbose_name='Описание компании')),
                ('logo', models.ImageField(upload_to='company_logos/', verbose_name='Логотип')),
                ('video', models.FileField(blank=True, null=True, upload_to='company_videos/', verbose_name='Видео')),
                ('history', models.TextField(verbose_name='История компании')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='company_certificate/', verbose_name='Сертификат')),
                ('account_details', models.TextField(verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
