# Generated by Django 5.0.4 on 2024-11-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_slidersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidersettings',
            name='auto',
            field=models.BooleanField(default=True, help_text='Автоматическое переключение слайдов (true или false)'),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='loop',
            field=models.BooleanField(default=True, help_text='Возможность листать слайдер по кругу (true или false)'),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='navs',
            field=models.BooleanField(default=True, help_text='Вывод стрелочек навигации (true или false)'),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='pags',
            field=models.BooleanField(default=True, help_text='Вывод пагинации (true или false)'),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='stopMouseHover',
            field=models.BooleanField(default=True, help_text='Остановка автопереключения при наведении мыши (работает только если auto=True)'),
        ),
        migrations.AlterField(
            model_name='slidersettings',
            name='auto_slide_delay',
            field=models.IntegerField(default=5, help_text='Время автопрокрутки слайдера в секундах'),
        ),
    ]
