# Generated by Django 5.0.4 on 2024-05-21 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='main.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='asked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.customer', verbose_name='Клиент'),
        ),
    ]
