# Generated by Django 5.0.4 on 2024-09-09 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_order_promo_code_promocode_discount_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
