# Generated by Django 5.0.4 on 2024-05-17 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_employee_description_employee_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='customers_cart', to='main.service'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Код заказа')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес проведения работ')),
                ('date_of_work', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проведения работ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.customer', verbose_name='Клиент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.employee', verbose_name='Сотрудник')),
                ('services', models.ManyToManyField(related_name='orders', to='main.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
