# Generated by Django 5.0.4 on 2024-05-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
