# Generated by Django 5.0.4 on 2024-05-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_coefficient',
            field=models.FloatField(default=1.0, verbose_name='Коэффициент скидки'),
        ),
    ]
